export const ROUTES = {
  ABOUT: 'about',
  ACCOUNT: 'account',
  ACCOUNT_ORDERS: 'account/orders',
  ACCOUNT_PROFILE: 'account/profile',
  ADMIN: 'admin',
  ADMIN_DASHBOARD: 'admin/dashboard',
  ADMIN_LOGIN: 'admin/login',
  ADMIN_ORDERS: 'admin/orders',
  ADMIN_POST_EDIT: 'admin/posts/:id',
  ADMIN_POST_NEW: 'admin/posts/new',
  ADMIN_POSTS: 'admin/posts',
  ADMIN_PRODUCT_EDIT: 'admin/products/:id',
  ADMIN_PRODUCT_NEW: 'admin/products/new',
  ADMIN_PRODUCTS: 'admin/products',
  CART: 'cart',
  CATALOGUE: 'catalogue',
  CHECKOUT: 'checkout',
  HOME: '',
  LOGIN: 'login',
  ORDER_CONFIRMED: 'order-confirmed',
  PRODUCT: 'product',
  PRODUCT_ID: 'product/:id',
  REGISTER: 'register',
} as const;

export type RouteKey = keyof typeof ROUTES;
